name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-actions@master
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-actions@master
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: pausch94/python-helloworld:latest
          platforms: linux/amd64,linux/arm64
